-- 1
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) 
	FROM ANIMAL_INS 
	GROUP BY ANIMAL_TYPE 
	ORDER BY ANIMAL_TYPE

-- 2
SELECT NAME, COUNT(NAME) 
	FROM ANIMAL_INS 
	WHERE NAME != 'NULL' 
	GROUP BY NAME 
	HAVING COUNT(NAME) > 1 
	ORDER BY NAME;

-- 3
SELECT  hour(datetime) hour,count(*)
	FROM animal_outs
	GROUP BY hour
	HAVING hour>=9 AND hour<=19
	ORDER BY hour ASC