-- 1
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME desc limit 1;

-- 2
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME LIMIT 1;

-- 3
SELECT COUNT(*) FROM ANIMAL_INS;

--4
SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS WHERE NAME != 'NULL';